# Generated by Django 5.0.2 on 2024-02-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0003_tag_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='image',
        ),
    ]
